### PR TITLE
Add option to compile UVVM Wishbone VIP.

### PR DESCRIPTION
**Pull request by m-kru**
Do not merge it yet, as I am still fighting with the UVVM to move the bitvis_vip_wishbone from UVVM_Community to UVVM repository https://github.com/UVVM/UVVM/issues/131. However, with PR available anyone can easily fetch it.

### CODE REVIEW

**Comment by umarcor** [comment]
@m-kru, please convert it to a draft, for preventing accidentally merging it.

**Comment by m-kru** [comment]
@umarcor how do I do that?

**Comment by m-kru** [comment]
As Wishbone BFM has been moved to the UVVM repository https://github.com/UVVM/UVVM/pull/140, this is no longer a draft.

**Comment by umarcor** [comment]
@m-kru, can you please add it to the `.ps1` script too?

**Comment by m-kru** [comment]
@umarcor I have added, but I am not able to test it.

**Comment by umarcor** [comment]
I tested it in the extended tests repo (well, in my fork): https://github.com/umarcor/ghdl-extended-tests/actions/runs/856856055. It seems to work. Still, I will let @paebbels review before merging.

**Comment by umarcor** [comment]
Nice! @m-kru, I'm happy that you could have this done in the end!

**Comment by m-kru** [comment]
@umarcor It was more social than technical challenge.

**Pull request merged**
