### PR TITLE
OpenBSD port

### PR DESCRIPTION
**Pull request by ams**
**Description**
Quick port to OpenBSD (6.9, AMD64) to use the mcode backend.  Test suite passes.

There are some egregious fixes here to make the test suite work on OpenBSD, like removing `--strip-trailing-cr` to diff, fixing some C99 specific things (OpenBSD defaults to C90) and other misc. changes.

The changes specifically to get GHDL working on OpenBSD are: 76fb1cf9d3a6d59fab5127b47f22ab08f2eaa801, 236ef20f39a7f519079e7ad6316b00a747980602  and 51d78ee6ffdcf308f2ee74f3d6f285eae595f02c.

Log files:

[configure.txt](https://github.com/ghdl/ghdl/files/6630447/configure.txt)
[testsuite.txt](https://github.com/ghdl/ghdl/files/6630445/testsuite.txt)
[compile.txt](https://github.com/ghdl/ghdl/files/6630446/compile.txt)

### CODE REVIEW

**Comment by tgingold** [comment]
Interesting.

I think I can merge the changes that are specific to OpenBSD.  Maybe I will reuse the macosx configuration for mcode rather than adding identical config files.

I am not sure about the purpose of the symlinks.  I suppose this was for locally running the testsuite.

The changes for diff will introduce failures for windows.  Maybe we should create a command in testenv.sh for diffing and not using strip trailing cr on OpenBSD.

**Comment by ams** [comment]
> Interesting.

:-)

I was slightly surprised that nothing strange was required.

> I think I can merge the changes that are specific to OpenBSD.  Maybe I will reuse the macosx configuration for mcode rather than adding identical config files.

No opinion, I started out that way and it worked.

> I am not sure about the purpose of the symlinks.  I suppose this was for locally running the testsuite.

Correct.

> The changes for diff will introduce failures for windows.  Maybe we should create a command in testenv.sh for diffing and not using strip trailing cr on OpenBSD.

Want me to write something up for that? I can't test it though, but maybe the CI pipeline will catch it?

**Comment by ams** [comment]
Pushed a fix that should DTRT when it comes to the diff command.

**Comment by tgingold** [comment]
I have just merged your patches with some minor changes.  Tell me if I broke something on OpenBSD.

Thank you for the PR!

**Comment by ams** [comment]
Just verified that the testsuite still passes, thanks!

**Comment by tgingold** [comment]
Great!  Thanks.

**Pull request closed without merging**
