### PR TITLE
fix: *gcc* build and run docker images are now named *gcc

### PR DESCRIPTION
**Pull request by 1138-4EB**
I did several modifications in ghdl/docker to simplify docker image names. Now:

- Images are not tagged `*mcode` and `*mcode-gpl`, the former is used only. It is fixed for this repo in #862.
- `ghdl/build:*gcc` and `ghdl/run:*gcc` images no longer have the version as a suffix. This PR is to fix this.

### CODE REVIEW

**Comment by tgingold** [comment]
Now merged, but still failing.

**Comment by 1138-4EB** [comment]
> Now merged, but still failing.

Yes. The failure with `*+gpl` is fixed in #862, not here. Let me explain:

Until yesterday, the same image was tagged `ghdl/build:stretch-mcode` and `ghdl/build:stretch-mcode-gpl`. The same applied to `ghdl/run:*`. I changed it, because it didn't make sense to have different names for the same content.

As a result, the `IMAGE=stretch+mcode+gpl` travis job now fails because it tries to use image `ghdl/build:buster-mcode-gpl`, which does not exist anymore. In #862, this is changed so that `gpl` or `synth` are provided in a different envvar. See https://github.com/ghdl/ghdl/blob/21bb312c6822e672842a4f3a7f194b867ee66a7a/.travis.yml#L13-L16

If you prefer, I can open a separate issue to fix the `gpl` jobs, which is unrelated to adding a job for `synth`.

**Comment by tgingold** [comment]
We can keep everything in #862, but it cannot be merged now due to a conflict.

**Comment by 1138-4EB** [comment]
Let's continue in #862...

**Pull request merged**
