### PR TITLE
Paebbels/preserve permissions

### PR DESCRIPTION
**Pull request by Paebbels**
# New Features

* Added a note on the nightly release page, where to find latest Docker images.
* Added a release job.

# Changes

* Split the Sphinx job into 2 jobs for HTML and LaTeX creation to optimize runtime (parallel execution).
* Replaced `actions/upload-artifact` by `pyTooling/upload-artifact`, to preserve file permissions by packing files in a tarball.
  * Kept `actions/upload-artifact` for already packaged `*.whl` and `*.pkg.tar.zst` files.
* Replaced `actions/download-artifact` by `pyTooling/download-artifact`, to restore artifact data from uploaded tarballs.
  * `pyTooling/download-artifact` can also handle (legacy) uploads from `actions/upload-artifact`.
  * Removed `chmod +x` calls from CI scripts.  
    (Previously needed in CI scripts to manually adjust file permissions after file transfer via artifacts.)
* Increased retention time on binaries to 7 days.  
  Intermediate artifacts (reports, results, HTML content, ...) are still 1 day.
* Upgraded to `r3` job templates from pyTooling.

# Bug Fixes

* Preserve file permissions when transferring artifacts from job to job.
* Preserve file permissions when assets are created from artifacts.  
  (Because artifacts preserved file permissions.)

### CODE REVIEW

**Comment by Paebbels** [comment]
Here is the pipeline run on ghdl/ghdl: https://github.com/ghdl/ghdl/actions/runs/12221092772  
And here the tagged run: https://github.com/Paebbels/ghdl/actions/runs/12221477949

I'm not sure if/how I can check embedded permissions in tar files on Windows. Maybe you could download a file and verify that assets have now permissions.

**Comment by Paebbels** [comment]
Some assets are missing ... I'm checking.

**Comment by Paebbels** [comment]
Hmmm, download was programmed manually via API, thus, I need to extract the intermediate tarballs here as well.

**Comment by Paebbels** [comment]
A new run is running: https://github.com/Paebbels/ghdl/actions/runs/12225959820
Here will be the release: https://github.com/Paebbels/ghdl/releases/testing

**Comment by Paebbels** [comment]
I verified the tarballs with `tar -tvf` and I can confirm that it contains x-bits.

**Comment by tgingold** [comment]
Is it OK to merge ?

**Comment by Paebbels** [comment]
I was about to say yes, but I found another bug. I'll set it to draft and debug. The used tar on macOS is BSD tar and it behaves differently then "normal" GNU tar.

**Comment by Paebbels** [comment]
I created some more tests for the new GitHub Actions `pyTooling/upload-artifact` and `pyTooling/download-artifact`. It's now heavily tested in each action's repository. In addition I run some tests of the GHDL pipeline and I also check a nightly release in my repository named `testing`.

Pipeline: https://github.com/Paebbels/ghdl/actions/runs/12361320626  
Release: https://github.com/Paebbels/ghdl/releases/tag/testing

I added a commit to not package already packaged files in an additional tarball. This applies to `*.whl` and `*.pkg.tar.zst` files. This will ease the usage of artifacts if users download these files instead of assets from `nightly` tag.

Please review and merge.

**Pull request merged**
