### PR TITLE
enable synth by default

### PR DESCRIPTION
**Pull request by eine**
In this PR, `enable_synth=false` is changed to `enable_synth=true`, so that synthesis features are enabled by default. Since `libghdl` is also enabled by default, after this PR is merged, any regular GHDL build will work with ghdlsynth-beta, without requiring GHDL to be rebuilt.

Synthesis features require GNAT>2017 and GCC>=8. Users with older versions might need to either update or use `--disable-synthesis` when configuring the build.

Currently, the job with `--gpl` fails if synthesis is enabled too (new default). @tgingold, shall I disable synth in this case or should the GPL variant not crash?

### CODE REVIEW

**Comment by tgingold** [comment]
It is because some aggregates are not supported by synthesis.

Disable synth for the gpl build.

**Comment by eine** [comment]
Done. GPL builds pass now. Ubuntu 16 jobs in Travis fail because of the known issue.

**Comment by eine** [comment]
@tgingold, shall we drop/deprecate Ubuntu 16 and use Ubuntu 18 instead?

**Comment by tgingold** [comment]
Yes, that makes sense.

**Comment by eine** [comment]
Done!

**Comment by tgingold** [comment]
Thanks!

**Pull request merged**
