### PR TITLE
Migrate from Travis and AppVeyor to GitHub Actions

### LINKED ISSUE #566: Migration from travis-ci.org
Travis is starting to merge travis-ci.org and travis-ci.com. GHDL is not affected, yet, but it will be in the following months:

> However, open source repositories will be migrated to travis-ci.com gradually, beginning at the end of Q2 2018

https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org

@tgingold, do we want to keep the build history? If not, you can send an e-mail and have the migration done now.

Apart from the domain, they are also going to change how authentication works. We should keep an eye on it:

> This creates the foundation for us to remove the repo-scoped OAuth login token, which is a common request.

https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

### PR DESCRIPTION
**Pull request by eine**
Close #566.

This is work in progress to deprecate Travis and AppVeyor as CI systems and *embrace* GitHub Actions.

- All the scripts in ` dist/travis` and ` dist/windows/appveyor` are moved to `dist/.deprecated/appveyor` and `dist/.deprecated/travis`, respectively, and none of them is used anymore. @tgingold, let me know if you prefer to just have them removed straightaway.

Relevant feature differences compared to the current Travis/AppVeyor solution:

- Startup time for Windows jobs is slightly slower, because MSYS2 is not installed by default. Then, compilation and test is 2x-3x slower than on AppVeyor.

- The list of GNU/Linux jobs is:

```
{ backend: mcode,     args: "" },
{ backend: mcode,     args: "--gpl" },
{ backend: mcode,     args: "--synth" },
{ backend: llvm-7,    args: "" },
{ backend: gcc-8.3.0, args: "" },
``` 

Hence, instead of testing the same backend(s) on multiple platforms, all the tests are executed on Debian (Buster). At the same time, a job for GCC backend is added, which was previously not included in the jobs list of this repo.

All of the other Debian, Ubuntu and Fedora platforms are still being tested in ghdl/docker; less frequently.

- I didn't implement any procedure to upload artifacts yet; neither to GitHub Releases nor through the Artifacts feature of GitHub Actions. This is because I don't know if we want to keep this feature with this limited job matrix. As proposed in #901, I believe that we can have a specific repo (ghdl/packaging) to provide pre-built tarballs. This is true for everyday *nightly* artifacts, and for tagged release artifacts too.

Nevertheless, I will keep this PR as a draft until we discuss this.

### CODE REVIEW

**Comment by Paebbels** [comment]
I would prefer to keep all systems in parallel until GitHub Actions is a stable product. It's still in beta phase.

Questions:
* Does GitHub list summaries of all test cases like AppVeyor?  
  Test name, time, execution time, status, ...
* Can the Windows version be selected?
  Windows 7, Windows 10 (Spring, Fall, ...), Windows Server 2016, ... ?

**Comment by 1138-4EB** [comment]
> I would prefer to keep all systems in parallel until GitHub Actions is a stable product. It's still in beta phase.

That's in 3 weeks, so we can wait. There are a couple of issues to fix in this PR yet:

- Installation time of MSYS2 can be reduced to 30s with https://github.com/numworks/setup-msys2.
- Uploading/releasing artifacts needs to be discussed (#901).

>     * Does GitHub list summaries of all test cases like AppVeyor?
>       Test name, time, execution time, status, ...

It is possible to define groups/blocks, but not nested. It is possible to time execution with bash features (as in Travis). There is no support for tracking the status of each case individually during execution.

Precisely, the same `testsuite.sh` is used for GNU/Linux, macOS and Windows (MINGW), instead of maintaining specific scripts for Windows.

See example output:

- https://github.com/1138-4EB/ghdl/actions
- https://github.com/1138-4EB/ghdl/commit/97aee23df7ca53bae98add32d75aa9233fb891d8/checks?check_suite_id=262516733

>     * Can the Windows version be selected?
>       Windows 7, Windows 10 (Spring, Fall, ...), Windows Server 2016, ... ?

It can be selected, but only a few environments are provided: https://help.github.com/en/articles/virtual-environments-for-github-actions

- Windows Server 2019
- Windows Server 2016 R2

**Comment by 1138-4EB** [comment]
I don't know why, running the testsuite on MINGW is failing now: https://github.com/1138-4EB/ghdl/runs/296926077#step:6:333

The error is produced in `gna/issue450` when trying to simulate:

https://github.com/ghdl/ghdl/blob/22775978be88c5ea8e5b740734e42eeb2fef0968/testsuite/gna/issue450/testsuite.sh#L18

File `vpi2.vpi` is compiled and it does exist. Moreover, same scripts work on my computer but fail on GHA.

It seems that the error is produced in:

https://github.com/ghdl/ghdl/blob/22775978be88c5ea8e5b740734e42eeb2fef0968/src/grt/grt-cvpi.c#L99-L112

https://github.com/ghdl/ghdl/blob/22775978be88c5ea8e5b740734e42eeb2fef0968/src/grt/grt-cdynload.c#L35-L39

@tgingold, I don't understand the TODO. However, I think that it might be related to the issue. Is it possible that `vpi2.vpi` depends on `libghdlvpi.dll` and for some reason it is not being found?

**Comment by tgingold** [comment]
Hum, that's possible.  Maybe put the directory of libghdlvpi.dll in the PATH, at least to check.

**Comment by 1138-4EB** [comment]
Precisely, I was going to comment that doing so works: https://github.com/ghdl/ghdl/pull/929/commits/83c5f745d940cb206aa4d8db26b52ccb24848123

**Comment by 1138-4EB** [comment]
Some further testing: https://github.com/1138-4EB/ghdl/commit/cf97f7bc81659cb5a0656f4b0f522f13233737f7/checks?check_suite_id=305727046#step:6:30

Source:

```
  echo ""
  echo "BEFORE:"
  ld --verbose | grep SEARCH_DIR
  echo "PATH: $PATH"
  export PATH=$PATH:"$(cd $(dirname $(which ghdl))/../lib; pwd)"

  echo ""
  echo "AFTER:"
  ld --verbose | grep SEARCH_DIR
  echo "PATH: $PATH"
```

Output:

```
BEFORE:
SEARCH_DIR("=/mingw32/i686-w64-mingw32/lib"); SEARCH_DIR("=/mingw32/lib"); SEARCH_DIR("=/usr/local/lib"); SEARCH_DIR("=/lib"); SEARCH_DIR("=/usr/lib");
PATH: /mingw32/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

AFTER:
SEARCH_DIR("=/mingw32/i686-w64-mingw32/lib"); SEARCH_DIR("=/mingw32/lib"); SEARCH_DIR("=/usr/local/lib"); SEARCH_DIR("=/lib"); SEARCH_DIR("=/usr/lib");
PATH: /mingw32/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/mingw32/lib
```

It seems that `SEARCH_DIR("=/mingw32/lib")` is correct. However, tests with vpi require it to be added to the PATH. That is not required locally. @tgingold, any guess about which sources are being used to search for the libs?

**Comment by tgingold** [comment]
Note that you could use ``ghdl --vpi-library-dir`` to directly get the vpi library dir.  That's simpler than:

>   export PATH=$PATH:"$(cd $(dirname $(which ghdl))/../lib; pwd)"

At execution time, windows searches dll on PATH.  I think that the SEARCH_DIR of ld is not really related to the issue.

**Comment by 1138-4EB** [comment]
The point is that I am trying to find why it works locally and not in GHA. Modifying the test to use `ghdl --vpi-library-dir` would apply to all the platforms. I feel it is unnecessary.

> At execution time, windows searches dll on PATH. I think that the SEARCH_DIR of ld is not really related to the issue.

On GHA Git Bash is provided by default. Since it does not include `pacman`, an Action is used to install MSYS2 in a temporal dir. I used SEARCH_DIR to test that having these two MINGW setups was not producing strange paths.

Nonetheless, locally the location of the libs is not on the PATH:

```
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/Program Files/Docker/Docker/resources/bin/
```

Still, there is no error. What search procedure is being used locally which is not working on GHA?

**Comment by 1138-4EB** [comment]
> Still, there is no error. What search procedure is being used locally which is not working on GHA?

Maybe using rpath can help: https://en.wikipedia.org/wiki/Rpath

**Comment by eine** [comment]
So, it took longer than I initially thought, but this PR is now ready for review/merge!

- All the GitHub jobs are merged into a single workflow.
  - Job Doc is moved from workflow 'doc' to 'push'.
  - `man` documentation is generated in job Doc and `ghdl.1` is uploaded along with nightly artifacts/assets. `scripts/man.sh` is removed.
- macOS artifacts are uploaded to the nightly pre-release too.
- Job Nightly is renamed to Release. The behaviour is as follows:
  - It is skipped on PRs.
  - On branches which are not "master, it is skipped unless it's a tagged commit.
  - On branches which are maste, the job is executed.
  - For untagged commits, artifacts are uploaded as assets of pre-release 'nightly'.
  - For tagged commits, artifacts are not uploaded:
    - If the tag is a semver release, a GitHub Release is created.
    - If the tag is a semver pre-release, creation of the release is skipped.
    - The filter to decide whether a tag is semver compliant and whether it's a release or a pre-release, is the following: https://github.com/eine/tip/blob/0b4083dfda2344f5e496d8df88e3a3159de81524/tip.py#L76. That's copied from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string.
- Publishing zipfiles from AppVeyor is deprecated. Building and executing tests is preserved, but deploying is removed.
- `.travis.yml` is removed.

**Comment by tgingold** [comment]
Thanks!

**Pull request merged**
