### PR TITLE
ci: enable libghdl on macOS, add LLVM job

### PR DESCRIPTION
**Pull request by eine**
As commented in [#848](https://github.com/ghdl/ghdl/issues/848#issuecomment-510205566), this PR removes `--disable-libghdl` from the Mac OS job in Travis.

### CODE REVIEW

**Comment by 1138-4EB** [comment]
This PR now updates Xcode from 9.4 to 10, and it also updates GNAT to 2019. However, the error is still the same: `ld: library not found for -lgnat-2019`.

---

There is a comment in [README.txt](http://mirrors.cdn.adacore.com/art/5cf1784731e87a39b16ab0f1):

> On Mac OS, GNAT Community 2019 requires Xcode version 10 or above to be
installed. Once you do have Xcode installed, if you still observe an error
of the form:
>
>  ld: library not found for -lSystem
>
> then you might have to execute the following:
>
>  xcode-select -s /Applications/Xcode.app/Contents/Developer

But it seems to have not effect. I tried installing GNAT to `/Applications/Xcode-10.app/Contents/Developer` instead of `gnat`; and setting `sudo xcode-select -s /Applications/Xcode-10.0.app/Contents/Developer`, with no success.

@tgingold, did libghdl ever work on macOS? Was it ever tested at all? Might the error be legit? E.g., there is some path missing for macOS in the makefile.

---

I also tried mounting the DMG image with `hdiutil` (instead of using 7z) and executing an automated installation with a `install_script.qs` as seen in [AdaCore/gnat_community_install_script](https://github.com/AdaCore/gnat_community_install_script), but the script seems to be outdated, and the installation hangs.

Some macOS user might help us here. @tmeissner, how do you get GNAT for macOS?

**Comment by tmeissner** [comment]
Mhm, some months ago since I've built ghdl. I don't know if there was a libghdl target at that time. But I also always use the GNAT community edition from Adacore without any changes.

**Comment by 1138-4EB** [comment]
> Mhm, some months ago since I've built ghdl. I don't know if there was a libghdl target at that time. But I also always use the GNAT community edition from Adacore without any changes.

If you did it some months ago, libghdl was not used/built. The makefile has had the libghdl target for long, but until a few weeks ago it was not built by default; you did need to execute it explicitly.

If possible, could you please try to build GHDL from `master`? Just the regular `./configure && make && make install` will suffice. No need to install any newer version of GCC or GNAT, just use the ones you have already installed. If it succeeds, it will mean that I must focus on 'fixing' Travis. If it fails, this is probably a task for @tgingold to fix in the makefile.

The error we get is `ld: library not found for -lgnat-201X` during `make`. But you might only notice it when running `make install`. See e.g.: https://travis-ci.org/ghdl/ghdl/jobs/557671321#721

**Comment by tmeissner** [comment]
Building the curnt HEAD of master works for me.

```
$ ./configure --with-llvm-config=/usr/local/Cellar/llvm\@5/5.0.2_1/bin/llvm-config --prefix=/usr/local
$ make
$ sudo make install
```

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/gnat-gpl-2015-x86_64-darwin/bin/../libexec/gcc/x86_64-apple-darwin13.4.0/4.9.3/lto-wrapper
Target: x86_64-apple-darwin13.4.0
Configured with: ../src/configure --enable-languages=ada,c,c++,objc --enable-lto --with-stage1-ldflags= --with-boot-ldflags=-static-libstdc++ --with-bugurl=URL:mailto:report@adacore.com --disable-nls --without-libiconv-prefix --disable-libmudflap --disable-libstdcxx-pch --disable-libada --enable-checking=release --disable-libsanitizer --disable-libcc1 --disable-libcilkrts --with-mpfr=/gnatmail/sandbox/gpl-2015/x86_64-darwin/mpfr/install --with-gmp=/gnatmail/sandbox/gpl-2015/x86_64-darwin/gmp/install --with-mpc=/gnatmail/sandbox/gpl-2015/x86_64-darwin/mpc/install --with-build-time-tools=/gnatmail/sandbox/gpl-2015/x86_64-darwin/gcc/build/buildtools/bin --prefix=/usr/local/gnat --build=x86_64-apple-darwin13.4.0
Thread model: posix
gcc version 4.9.3 20150428 (for GNAT GPL 2015 20150428) (GCC) 
```

**Comment by 1138-4EB** [comment]
It seems that the codebase is correct (at least with LLVM backend). Hence, this must be a problem with the Travis setup. Also, it seems that latest versions of GNAT are not required, since you used 2015. Thanks a lot! This information is very useful for us.

**Comment by eine** [comment]
This PR is now rebased on top of #1072. Unfortunately, the issue with libghdl on macOS is not solved yet.

**Comment by Arcnor** [comment]
So what I've found so far, which might or might not be useful. I'm not sure how `gnatlink` works at all, but I've SSH'd into the build machine to see the location of libs and this is what I can see. From the `gnat` directory:

```
./libexec/spark/lib/xmlada/xmlada_input.relocatable/libxmlada_input_sources.dylib
./libexec/spark/lib/xmlada/xmlada_schema.relocatable/libxmlada_schema.dylib
./libexec/spark/lib/xmlada/xmlada_sax.relocatable/libxmlada_sax.dylib
./libexec/spark/lib/xmlada/xmlada_unicode.relocatable/libxmlada_unicode.dylib
./libexec/spark/lib/xmlada/xmlada_dom.relocatable/libxmlada_dom.dylib
./libexec/spark/lib/gnatcoll.relocatable/libgnatcoll.dylib
./libexec/spark/lib/gnat_util/relocatable/libgnat_util.dylib
./libexec/spark/lib/gcc/x86_64-apple-darwin17.7.0/8.3.1/rts-native/adalib/libgnarl-2019.dylib.dSYM/Contents/Resources/DWARF/libgnarl-2019.dylib
./libexec/spark/lib/gcc/x86_64-apple-darwin17.7.0/8.3.1/rts-native/adalib/libgnarl-2019.dylib
./libexec/spark/lib/gcc/x86_64-apple-darwin17.7.0/8.3.1/rts-native/adalib/libgnarl.dylib
./libexec/spark/lib/gcc/x86_64-apple-darwin17.7.0/8.3.1/rts-native/adalib/libgnat.dylib
./libexec/spark/lib/gcc/x86_64-apple-darwin17.7.0/8.3.1/rts-native/adalib/libgnat-2019.dylib.dSYM/Contents/Resources/DWARF/libgnat-2019.dylib
./libexec/spark/lib/gcc/x86_64-apple-darwin17.7.0/8.3.1/rts-native/adalib/libgnat-2019.dylib
./lib/libgnat_util.dylib
./lib/gnatcoll.relocatable/libgnatcoll.dylib
./lib/libgnatcoll.dylib
./lib/libgcc_ext.10.4.dylib
./lib/libgcc_s_ppc64.1.dylib
./lib/libaws.dylib
./lib/libgpr.dylib
./lib/libgcc_s_x86_64.1.dylib
./lib/libgcc_ext.10.5.dylib
./lib/libgcc_s.1.dylib
```

So that `gnat-2019` library is at `gnat/libexec/spark/lib/gcc/x86_64-apple-darwin17.7.0/8.3.1/rts-native/adalib/`. Now it will be nice to understand how the library path is being passed to `gnatlink`. Wild guess, but if that `x86_64-apple-darwin17.7.0` directory is based off the machine's `uname` or similar it might not match, although I doubt that's the actual problem.

In any case, I think another thing to test might be running `gnatlink` with `-v -v`, which might tell us the actual command passed to `gcc`

**Comment by Arcnor** [comment]
BTW there is another failure way before it tries to link https://github.com/ghdl/ghdl/pull/867/checks?check_run_id=1805280440#step:4:409

```
gnatlink: error when calling /Users/runner/work/ghdl/ghdl/gnat/bin/gcc
```

Any idea about that one?

**Comment by eine** [comment]
> So that `gnat-2019` library is at `gnat/libexec/spark/lib/gcc/x86_64-apple-darwin17.7.0/8.3.1/rts-native/adalib/`. Now it will be nice to understand how the library path is being passed to `gnatlink`. Wild guess, but if that `x86_64-apple-darwin17.7.0` directory is based off the machine's `uname` or similar it might not match, although I doubt that's the actual problem.

As you say, I doubt that's the actual problem. I think that adalib is used regardless of `libghdl`, so the dependencies are found. However, it might be that linking to the lib dynamically requires some additional argument to gnatlink.

> In any case, I think another thing to test might be running `gnatlink` with `-v -v`, which might tell us the actual command passed to `gcc`

Feel free to fork this branch and add that. As soon as you push it to your fork, CI should run.

> gnatlink: error when calling /Users/runner/work/ghdl/ghdl/gnat/bin/gcc
>
> Any idea about that one?

I had not seen that (or maybe I don't remember). I guess that's what we should fix/understand first.

**Comment by Arcnor** [comment]
> As you say, I doubt that's the actual problem. I think that adalib is used regardless of libghdl, so the dependencies are found. However, it might be that linking to the lib dynamically requires some additional argument to gnatlink.

I don't think extra arguments are needed (except for the path argument, of course), it's clearly trying to find that library already

> Feel free to fork this branch and add that. As soon as you push it to your fork, CI should run.

Yeah, all my tests have been run on my fork, that's how I managed to SSH into GH build machines

So new info. As expected, library paths seem wrong:

```
Library search paths:
        /Users/runner/work/ghdl/ghdl/pic/
        /Users/runner/work/ghdl/ghdl/pic/
        /Users/runner/work/ghdl/ghdl/gnat/lib/gcc/x86_64-apple-darwin17.7.0/8.3.1/adalib/
        /Users/runner/work/ghdl/ghdl/gnat/lib/gcc/x86_64-apple-darwin17.7.0/8.3.1
        /Users/runner/work/ghdl/ghdl/gnat/lib/gcc
        /Users/runner/work/ghdl/ghdl/gnat/lib
        /Applications/Xcode_12.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib
Framework search paths:
        /Applications/Xcode_12.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/
```

If you look closely, those paths are not the same where the libs are:

```
// Wrong
gnat/lib/gcc/x86_64-apple-darwin17.7.0/8.3.1/adalib/
// Right
gnat/libexec/spark/lib/gcc/x86_64-apple-darwin17.7.0/8.3.1/rts-native/adalib/
```

I'm still trying to figure out why, will update if I find out something else

**Comment by Arcnor** [comment]
Ok, I found out something. I think everything works if we don't do that "cleanup" stage on the libada script. I'm not really sure why you're deleting a lot of libraries and things like that there. Is it because of space concerns? Because I think that's causing all this trouble...

**Comment by eine** [comment]
> Ok, I found out something. I think everything works if we don't do that "cleanup" stage on the libada script. I'm not really sure why you're deleting a lot of libraries and things like that there. Is it because of space concerns? Because I think that's causing all this trouble...

Please, go ahead and remove that in your tests. I believe it exists "for historical reasons". Some time ago, the tests were executed on Travis only and the installation path of GNAT was cached. I believe that Tristan's purpose was to reduce cache save/load time. However, it is ok to remove it now, and we will then think how to optimise it again. Currently the GNAT installation is not cached on GitHub Actions, so there is not space/performance concern.

**Comment by Arcnor** [comment]
> Please, go ahead and remove that in your tests. I believe it exists "for historical reasons". Some time ago, the tests were executed on Travis only and the installation path of GNAT was cached. I believe that Tristan's purpose was to reduce cache save/load time. However, it is ok to remove it now, and we will then think how to optimise it again.

I see. Yeah, I'm running a new build with that removed, but I did it "manually" inside the VM and suddenly everything worked (well, at least this part we're testing here).

> Currently the GNAT installation is not cached on GitHub Actions, so there is no space/performance concern.

That's another thing I think we should change. Currently installing `gnat` takes a good chunk of build time, so adding a cache seems like a no brainer (we have 5GB) but of course, I'll wait to see what you think about it.

Will comment back in a few minutes to let you know about results :)

**Comment by Arcnor** [comment]
This was indeed the fix. Do you want me to open a new PR or do you just want to remove those lines from the file yourself?

**Comment by eine** [comment]
Please, open a PR, so that I can have a better look at it and we can iterate easier. It sounds nice to add caching if you are up to it! https://github.com/ghdl/ghdl/blob/master/.github/workflows/Test.yml#L420-L422

**Comment by Arcnor** [comment]
Ok, will open a PR shortly, and I'll probably open it against your fork, so we can keep the whole "timeline" in case there is a problem in the future.

**Comment by eine** [comment]
> but I did it "manually" inside the VM and suddenly everything worked (well, at least this part we're testing here).

BTW, although off-topic, I'd be glad if you could any reference about how to do this. I know it's possible, but I haven't looked into the details. I'd be glad if you allow me to be lazy and just learn from your workflow.

**Comment by eine** [comment]
> Ok, will open a PR shortly, and I'll probably open it against your fork, so we can keep the whole "timeline" in case there is a problem in the future.

You can create it off the master branch of this repo. No need to build on top of my branch/fork, because my contribution is negligible here. The relevant content is the one you are doing.

**Comment by Arcnor** [comment]
> You can create it off the master branch of this repo. No need to build on top of my branch/fork, because my contribution is negligible here. The relevant content is the one you are doing.

My thinking was that if you update your branch (this one the PR is based of) my commits will appear here and everything will be tied, I think the whole "how we got here" is as important as the fix itself :).

> BTW, although off-topic, I'd be glad if you could any reference about how to do this. I know it's possible, but I haven't looked into the details. I'd be glad if you allow me to be lazy and just learn from your workflow.

Sure, it's really easy, just check here https://github.com/marketplace/actions/debugging-with-tmate. Basically, add the `tmate` step & ssh into it. I couldn't get the web version to work, but just using plain old `ssh` works the same. You can see my build as an example https://github.com/Arcnor/ghdl/runs/1813862328 (the "Setup tmate session" step)

**Comment by eine** [comment]
> My thinking was that if you update your branch (this one the PR is based of) my commits will appear here and everything will be tied, I think the whole "how we got here" is as important as the fix itself :).

Fair enough :wink: That will work too!

> Sure, it's really easy, just check here [github.com/marketplace/actions/debugging-with-tmate](https://github.com/marketplace/actions/debugging-with-tmate). Basically, add the `tmate` step & ssh into it. I couldn't get the web version to work, but just using plain old `ssh` works the same. You can see my build as an example [Arcnor/ghdl/runs/1813862328](https://github.com/Arcnor/ghdl/runs/1813862328) (the "Setup tmate session" step)

Thank you so much!

**Comment by Arcnor** [comment]
Ok, I've ran out of time for today, but I have a branch with all changes, including a matrix build for mcode & llvm. However, I'm having some silly trouble with that one as you can see here https://github.com/Arcnor/ghdl/runs/1814275480?check_suite_focus=true#step:5:921

Issue is simply that `$BACK` doesn't seem to be set at https://github.com/Arcnor/ghdl/blob/mac-libghdl/scripts/ci-run.sh#L434 although my bash-fu doesn't seem to be enough to figure out why in a hurry.

In any case, building works so after that's fixed I think all changes can be merged into this one and the rest of the changes needed can be started, if any.

**Comment by eine** [comment]
> although my bash-fu doesn't seem to be enough to figure out why in a hurry.

You can blame that on me. The `ci-run.sh` script is not easy to understand because it handles builds for all three backends, apart from using containers (building images) for Linux jobs. The script calls itself for building, and that's where BACK is defined, but not when running the testsuite.

Anyway, I did some cleanup, I enabled all test suites and everything seems to be working. Caching is also working nicely.

Muchas gracias!

**Comment by Arcnor** [comment]
Awesome, glad it worked out in the end :).

¡De nada!

**Comment by diogratia** [comment]
There was a work around found last June without knowing the cause was the install-ada.sh script.

The missing -lgnat-2009 reference could be trimmed by the middle of these three lines:

```none
       gnat/lib/gcc/x86*/*/rts-native/adalib/lib*.dSYM \
       gnat/lib/gcc/x86*/*/rts-native/adalib/*.dylib \
       gnat/lib/gcc/x86*/*/rts-native/adalib/lib*_pic.a \
```
Removing these three lines from the rm list:
```none
rm -rf gnat/share/{themes,icons} \
       gnat/share/{man,info,doc,examples,gpr,gprconfig,gnatcoll} \
       gnat/share/gps \
       gnat/share/gdb* gnat/share/glib* gnat/share/gcc-*/python \
       gnat/etc/fonts gnat/etc/gtk* \
       gnat/include/{asis,aunit,gnat_util,gnatcoll,gpr,xmlada} \
       gnat/include/aws* gnat/include/pycairo gnat/include/python* \
       gnat/include/pygobject* gnat/include/gdb \
       gnat/include/c++ \
       gnat/lib/{aunit,gnat,gnat_util,gnatcoll,gpr,gps,xmlada} \
       gnat/lib/aws* gnat/lib/girepository* gnat/lib/gtk* \
       gnat/lib/python* \
       gnat/lib/gcc/x86*/*/{gcc-include,plugin,install-tools} \
       gnat/lib/gcc/x86*/*/rts-ios-simulator \
       gnat/libexec/gprbuild \
       gnat/libexec/gcc/x86*/*/{plugin,install-tools} \
       gnat/bin/aws* gnat/bin/gps* gnat/bin/gcov* \
       gnat/bin/gnat2* gnat/bin/xml2* gnat/bin/gnatcoll* \
       gnat/bin/gnat{doc,metric,pp,stub,prep,test,check,elim,inspect,find,kr} \
       gnat/bin/gnat{xref,name} \
       gnat/bin/gpr* gnat/bin/templates* gnat/bin/web* gnat/bin/wsdl* \
       gnat/bin/{gdb,cpp,c++,g++} gnat/bin/x86_64-* \
       gnat/lib/libcc1* gnat/lib/libgomp* gnat/lib/libitm* gnat/lib/libasan* \
       gnat/lib/libatomic* gnat/lib/libobjc* gnat/lib/libssp* \
       gnat/lib/libstdc++* gnat/lib/libubsan* gnat/lib/libsupc++* \
       gnat/lib/libxmlada* \
       gnat/libexec/gcc/x86*/*/{cc1obj,cc1plus,lto1}
```
allows libghdl to be generated while still saving disk space.

The work around last June without configuring --disable-libghdl was to logically link libgnat.a to libgnat-2019.a in `gnat/lib/gcc/x86_64-apple-darwin17.7.0/8.3.1/adalib`. 

The space saving was desirable having multiple llvm clang-llvm versions and AdaCore gnat versions resident.

**Comment by eine** [comment]
@diogratia, do you actually use the `install-ada.sh` script locally? I thought it was used for CI only. If you think we should bring the trimmed rm list back, it's sensible to do so.

**Comment by diogratia** [comment]
I extracted the rm part of the script and redirected the gnat prefix with a variable. I've tried the install-ada.sh script before. 

If ghdl gets much bigger you might find it desirable to conserve disk space for builds.  

I'm also moving to a Macbook Air M1 with a smallish SSD (ghdl and gtkwave run using Rosetta 2).  Don't use gnat for anything else.

**Comment by Arcnor** [comment]
When working on the fix, I realized the only problem was the `dylib` & related files removal. However, I decided to avoid the whole "cleanup" because it might cause issues in the future. For sure, removing the `doc` or some images "should" not cause any problems, but IMHO developer time is more valuable than disk space, and this kind of removal might backfire in the future.

**Comment by eine** [comment]
@Arcnor, since the script does not use cli options at the moment, we can easily make it optional. `if [ "x$1" = "x--rm" ]`. Then, it's up to the caller to set that option.

While you are right about developer time, this also affects CI time. From the developer point of view, we had not found this issue before. Since we did it now, we know what to expect in case it's raised again. Anyway, I think we should evaluate the gain. If it's less than 20-30s, we can keep it all.

**Pull request merged**
