### PR TITLE
Provide initial skeleton for libghdl documentation.

### PR DESCRIPTION
**Pull request by m-kru**
Not a lot of useful information, but some questions, that I hope @tgingold will be able to answer.

### CODE REVIEW

**Comment by tgingold** [comment]
So how to proceed ?  Should this PR be merged and then answered by another merge ?  Or should the questions be answered in this PR ?

**Comment by m-kru** [comment]
@tgingold I think it would be better to answer in this PR.

**Comment by eine** [comment]
@m-kru, did you close this on purpose? Or was it an effect of having your master branch updated? https://github.com/ghdl/ghdl/commit/cc416a50e817fbdaaa5579420051dffa258a40bf seems to be gone from your fork.

**Comment by m-kru** [comment]
@eine ohh, I have not realized. I closed it by accident by updating master on my fork.

**Comment by m-kru** [comment]
I was not able to reopen, so I have created new issue: https://github.com/ghdl/ghdl/pull/1445

**Pull request closed without merging**
