### PR TITLE
Fixed library compilation on Windows

### PR DESCRIPTION
**Pull request by Paebbels**
Fixed library compilation on Windows due to changes in 7ef79a53.

### CODE REVIEW

**Comment by Paebbels** [comment]
Oh I remember ...
AppVeyor uses the makefiles in MinGW to build GHDL for Windows. Te PowerShell flow is not used on AppVeyor due to problems in executing the Ada Core compiler on Windows Server 2016.

**Comment by tgingold** [comment]
Thanks.

Do you think it is possible to execute the msys2 Ada compiler from PowerShell ?

**Comment by Paebbels** [comment]
I could run the Ada compiler from PowerShell in MinGW32 and/or MinGW64. But the results of the compilation are not running standalone.

We had a discussion some time ago, that we would need to ship the resulting binaries and 5-7 DLLs with ghdl.exe to have a standalone system.

As I now understand how ArchLinux / pacman packages work, I think we can package GHDL for the MinGW pacman system to get it installed diretly in MinGW.

**Comment by tgingold** [comment]
> On 13 Feb 2018, at 21:18, Patrick Lehmann <notifications@github.com> wrote:
> 
> I could run the Ada compiler from PowerShell in MinGW32 and/or MinGW64. But the results of the compilation are not running standalone.
> 
> We had a discussion some time ago, that we would need to ship the resulting binaries and 5-7 DLLs with ghdl.exe to have a standalone system.

Did you try to link using -static so that DLL aren't used ?

**Pull request merged**
