### PR TITLE
doc: update instructions about GCC and GNAT Community installation

### PR DESCRIPTION
**Pull request by rodrigomelo9**
I updated instructions about GNAT Community Edition installation.

### CODE REVIEW

**Comment by rodrigomelo9** [comment]
I was helping with a Centos7 compilation, using GCC as backend, and I would like to perform some more improvements to the instructions:
* Add a comment after *`gcc-ada` or `gcc-gnat`*: *(which could be outdated)*
* *can be downloaded anonymously from* what about to remove anonymously? It sounds **illegal** when not.

And what about to provides an example link to the GCC sources into `development/building/GCC.html#build-gcc`? I used https://codeload.github.com/gcc-mirror/gcc/tar.gz/releases/gcc-8.3.0.

**Comment by rodrigomelo9** [comment]
I realized that only `x86 GNU Linux (64 bits)` is available at https://www.adacore.com/download, so also the comment *(2014, or later; for x86, 32 or 64 bits).* must be updated. You can't choose a version, I mean, only 2020 is available there.

**Comment by eine** [comment]
> I realized that only `x86 GNU Linux (64 bits)` is available at [adacore.com/download](https://www.adacore.com/download), so also the comment _(2014, or later; for x86, 32 or 64 bits)._ must be updated. You can't choose a version, I mean, only 2020 is available there.

There is a link at the botton to other versions: https://www.adacore.com/download/more. There, you can see that packages did need to be extracted until 2017. Then, executable installers are distributed.

Therefore, I think that this PR should account for both. That is, instead of modifying the text, add a clarification/note. 

> Add a comment after gcc-ada or gcc-gnat: (which could be outdated)

Agree. We should clarify why would users want to use AdaCore's GNAT instead of gcc-ada or gcc-gnat.

> can be downloaded anonymously from what about to remove anonymously? It sounds illegal when not.

Anonymously means that users don't need to register in order to get the link, which is still an annoying practice in many companies. I think it is a common term for services/permissions. Anyway, feel free to reword it.

> And what about to provides an example link to the GCC sources into development/building/GCC.html#build-gcc? I used codeload.github.com/gcc-mirror/gcc/tar.gz/releases/gcc-8.3.0.

That's just a mirror. I don't think it's necessary to explain users how to get GCC sources. If someone is building GHDL with GCC backend, they must already be experienced enough so that finding the sources is negligible. We do already provide a link to GCC site in https://ghdl.github.io/ghdl/development/building/index.html.

**Comment by rodrigomelo9** [comment]
> Therefore, I think that this PR should account for both. That is, instead of modifying the text, add a clarification/note.

I add a HINT clarifying the situation. Let me know if HINT is ok for that or what to use.

> Anonymously means ...

I know, but I prefer to be clear (changed by *without registration*) and avoid to sound illegal.

> That's just a mirror. I don't think it's necessary to explain users how to get GCC sources.

This part (GCC installation) was one of the main problems of the user that I helped. I had no present how to get the GCC sources, so I checked the CI of the project to get a link (which was no straight forward, due that the version in the link is a variable in `ci-run.sh`). What about at least a link to the GCC mirrors (https://gcc.gnu.org/mirrors.html)? I only want to improve the user experience when GCC backend is needed. Let me know what you think about and in case of agree, if you prefer a separate PR (this change is in another file, doc/development/building/GCC.rst).

**Comment by rodrigomelo9** [comment]
Hi @eine, I added a link to the *GCC mirror sites* into doc/development/building/GCC.rst.

**Comment by eine** [comment]
Thanks!

**Pull request merged**
