### PR TITLE
doc: Add indications that ghdl/docker exsists to README.md

### PR DESCRIPTION
**Pull request by gasparka**
Discussion in #166 
* Docker badge
* Two links to ghdl/docker, with minor rewording - feel free to reword again :)

### CODE REVIEW

**Comment by 1138-4EB** [comment]
LGTM.

**Comment by gasparka** [comment]
I linked to https://github.com/ghdl/docker, i guess it is the best place to land when someone is interested in the images.

**Comment by 1138-4EB** [comment]
Thanks. One of the jobs in Travis failed because of a non-related issue. I restarted it.

**Comment by tgingold** [comment]
Thanks!

**Pull request merged**
