### PR TITLE
Add a code of conduct

### LINKED ISSUE #841: Add a code of conduct
**Is your feature request related to a problem? Please describe.**
The development of any software may lead to conflicts. It would be great to have a set of rules by which it could be independently decided what is too much and what are the consequences of that behaviour.

**Describe the solution you'd like**
Add a code of conduct or start a discussion on that topic.

**Describe alternatives you've considered**
To rely on people's common sense. :-)

**Additional context**
Personally, I thought that code of conducts are useless until recently when I figured out that if there is a chance for incoming people to behave better, it is worth it.

### PR DESCRIPTION
**Pull request by dominiksalvet**
**Description**
I have added the [No Code Of Conduct](https://github.com/domgetter/NCoC) to the project. Resolves #841.

:rotating_light: Before submitting your PR, please read [contribute](http://ghdl.readthedocs.io/en/latest/contribute.html#fork-modify-and-pull-request) in the [Docs](http://ghdl.readthedocs.io/en/latest/index.html), and review the following checklist:

- [x] DO indicate which issues are either fixed or closed by this PR. See [GitHub Help: Closing issues using keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

**Further comments**

I created the *CODE_OF_CONDUCT.md* file in the *.github/* directory as I have though that it is the most appropriate directory considering the current project structure. However, if you want to move the file, feel free to do so. If you have any comments, let me know.

### CODE REVIEW

**Comment by 1138-4EB** [comment]
Thanks @dominiksalvet.

> I created the CODE_OF_CONDUCT.md file in the .github/ directory as I have though that it is the most appropriate directory considering the current project structure. However, if you want to move the file, feel free to do so. If you have any comments, let me know.

FTR, putting the CoC markdown file in `.github/` is supported: https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project.

So it's ok, and preferred in this case, indeed.

---

Just some minor issues:

- Why are sentences separated by double whitespaces? I'd suggest any of:
  - Using a single whitespace.
  - Using a list instead. I.e.: `This project adheres to No Code of Conduct:<newline>-We are all adults.<newline>-We accept anyone's contributions.<newline>Nothing else matters.<newline>...`
  - Using semicolons: `This project adheres to No Code of Conduct: we are all adults; we accept anyone's contributions; nothing else matters.<newline>...`
- I'd keep the exclamation mark in the last sentence.

**Comment by dominiksalvet** [comment]
@1138-4EB I am sorry, it was a verbatim copy-paste from it's [original form](https://raw.githubusercontent.com/domgetter/NCoC/master/CODE_OF_CONDUCT.md).

Well, to keep it authentic, I will replace double whitespace characters with single ones.

> * I'd keep the exclamation mark in the last sentence.

Keep? I am sorry but I don't see any exclamation mark in the whole code of conduct. Do you want to add one?

**Comment by 1138-4EB** [comment]
> Keep? I am sorry but I don't see any exclamation mark in the whole code of conduct. Do you want to add one?

Oh. I thought that you have copied it from the [README](https://github.com/domgetter/NCoC/blob/master/README.md#what-if-we-all-agreed) by taking the first sentence of each item in the list. As you see, *Nothing else matters!* has an exclamation mark there.

Anyway, since I see that you copied it from another file, just removing the double whitespaces will suffice, as long as you are ok with it.

**Comment by tgingold** [comment]
Thanks.

**Pull request merged**
