### PR TITLE
Executing Python unit tests in Parallel Processes

### PR DESCRIPTION
**Pull request by Paebbels**
This PR contains:
* Parallel execution with `pytest` and its plugin `pytest-forked` is now possible.  
  This works around the problem for independent unit testing that `libghdl` can only be initialized once.
* `pytest`s strange/strict naming conventions were disabled via `pytest.ini` in `testsuite/pyunit` to comply with normal unittest naming rules.
* `testsuite.sh` was adjusted to run from within `testsuite` directory.
* All 5 testcases are now found and executed.

### CODE REVIEW

**Comment by Paebbels** [comment]
@umarcor tests on MSYS2 / MinGW fail because `pytest-forked` considers these platforms to not support `fork`. Any ideas?

**Comment by umarcor** [comment]
@Paebbels I guess we should install pytest-forked through pacman, instead of having it in the requirements file: [`mingw-w64-x86_64-python-pytest-forked`](https://packages.msys2.org/package/mingw-w64-x86_64-python-pytest-forked?repo=mingw64).

**Comment by Paebbels** [comment]
**Last update for today:**
* MSYS2 has fork support (`os.fork(...)`) in Python 3
* MinGW64 has not.

**Comment by Paebbels** [comment]
@umarcor I pushed another tiny change to the branch.

**Comment by tgingold** [comment]
I am working on library finalization so that it could be restarted.

**Comment by tgingold** [comment]
I am testing my changes, so it should be pushed soon (hopefully today).

I am OK with this PR except for the `--forked` part as it won't be needed anymore.

**Comment by umarcor** [comment]
@Paebbels, please comment https://github.com/ghdl/ghdl/blob/master/.github/workflows/push.yml#L17-L32 out. We will deal with formatting later, after we are done with this series of pyGHDL/CI reorganisation PRs.

**Comment by Paebbels** [comment]
@tgingold this is ready for a merge.

**Pull request merged**
