### PR TITLE
Parallelize suite_driver with xargs -P

### PR DESCRIPTION
**Pull request by DanielG**
The vests suite is still sequential since it doesn't seem to go through
suite_driver which is still limiting the speedup.

### CODE REVIEW

**Comment by tgingold** [comment]
Why not but there is `gna/testsuite.py` which already run tests in parallel.
I would prefer to use the python script, it is easier to maintain.
WDYT ?

**Comment by DanielG** [comment]
I don't speak python so to me it's certainly less maintainable ;)

If you really want something maintainable I'd go with a generic test driver framework like TAP then you don't have to home grow and maintain it to begin with. https://en.wikipedia.org/wiki/Test_Anything_Protocol

**Comment by Paebbels** [comment]
I would prefer a testsuite run by `pytest`.

Besides pure execution, it would give us reports, statistics etc.

**Comment by DanielG** [comment]
pytest looks to be in Debian so that works for me. I'd still like to get this merged in the mean time since it provides an immediate benefit at essentially no cost. I'm certainly not going to go and port the testsuite to some other framework ;)

**Comment by tgingold** [comment]
Fine.

**Pull request merged**
