### PR TITLE
Removed VUnit pre-compile scripts from GHDL.

### PR DESCRIPTION
**Pull request by Paebbels**
As requested in several issues (#353, #534, #528) the VUnit pre-compile scripts get removed by accepting this MR. The documentation was adjusted too.

### CODE REVIEW

**Comment by Paebbels** [comment]
This MR looks a bit strange. I used the online conflict solver ...

@tgingold Please review my changes.

**Comment by tgingold** [comment]
Manually merged.

Thanks!

**Comment by Paebbels** [comment]
So even after my online conflict resolution, you needed to merge it manually, too?
If so, I don't understand that online feature ...

**Comment by tgingold** [comment]
Yes, apparently it cannot cope with resolve commits.

**Pull request closed without merging**
